version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: tor
      POSTGRES_DB: testdb
    ports:
      - '5432:5432'
